### ISSUE TITLE
Diagnostic Tools Time Out

### ISSUE THREAD

**Issue by bobstrecansky** [akamai-open/api-kickstart#22]
I'm trying to use the error reference parser in order to get the output from the errortranslator.  I get authenticated properly and other calls work for me (i've tested VerifyCdnIPData).  The error translator always times out on any request (i've tried it both in Python and PHP; PHP code included).

PHP code:
https://gist.github.com/bobstrecansky/b7a5e8b67e278b7c0ff7

Error Output:
https://gist.github.com/bobstrecansky/428c11692eadb638e838

**Comment by maglietti** [comment]
Hi Bob,

We are experiencing issues internally with the errorTranslator API. Internal server request are timing out and that, in turn, is causing your client error. 

I made successful calls to the API today, but the responses are taking a very long time. Please increase the timeout for your client to at least 300 seconds and see if that helps. 

I am also watching the CCare ticket that you opened yesterday. I am in discussions with the internal development teams responsible for the API origin code, we are hoping to have this issue resolved this week. 

-- Michael

**Comment by maglietti** [comment]
The internal issue that was causing timeouts has been resolved. However, the errorTranslator is still running very slow and seems to be taking 30 to 40 seconds on average to respond. 

Please reopen this issue if you are having timeout problems again.
