### ISSUE TITLE
Need help to integrate akamai video with angular app

### ISSUE THREAD

**Issue by pgangwani** [akamai-open/api-kickstart#47]
Hello Team, 
I am not sure of this is right place to get my query addressed by appropriate team. We are working on angular app with AEM in backend leveraging akamai for video integration in our app . 
I am unable to find an angular example for akamai video integation. Could any one of your dev team or anyone can help me.
Thanks,
Pawan
pawangangwani0@gmail.com
pgangwani2@sapient.com

**Comment by ktyacke** [comment]
Hello,
The best place for this type of question is on the Akamai Developer Community: https://community.akamai.com/community/developer  

Thanks,

Kyle
