### ISSUE TITLE
Variable reference error in config.py

### ISSUE THREAD

**Issue by monokal** [akamai-open/api-kickstart#52]
When using `from config import EdgeGridConfig` I'm seeing a `local variable 'arguments' referenced before assignment` error. This seems to be because `arguments[argument]` is referenced on line 64 before it's assignment on line 69.

See reference (last line - 64):
```python
        for argument in config_values:
        	if config_values[argument]:
        		if config_values[argument] == "False" or config_values[argument] == "True":
        			parser.add_argument('--' + argument, action='count')
        		parser.add_argument('--' + argument)
        		arguments[argument] = config_values[argument]
```

See assignment (69):
```python
arguments = vars(args)
```

The only modification I've made to the file is to add `conflict_handler` to `parser` otherwise I hit conflict errors when using `argparse` in my own script (perhaps there's a better way like moving the parser in to a `if __name__ == "__main__":` block?):
```python
# Added conflict_handler to support pyakamai.
parser = argparse.ArgumentParser(
    description='Process command line options.',
    conflict_handler="resolve"
)
```
On an unrelated note, there's also a whole bunch of unused imports which could probably be cleaned up. Out of the 10 imports only `argparse` and `logging` are used. I'm happy to open a PR with your guidance on the variable reference error.

Edit: There seems to be another module here: https://github.com/akamai-open/AkamaiOPEN-edgegrid-python

Are these examples deprecated as they don't appear to make use of the above module's functionality.

**Comment by synedra** [comment]
I've updated the code to fix this issue.  Thanks, Kirsten
