### ISSUE TITLE
http_calls.py fails when it faces a 403 error

### ISSUE THREAD

**Issue by shalomcarmel** [akamai-open/api-kickstart#53]
Line 56 today is 
`                    error_msg +=  "ERROR: Problem details: %s\n" % result["detail"]`

which fails as there is no "detail" key. There is however a "details" key. 
Recommended to change to 
`                    error_msg +=  "ERROR: Problem details: %s\n" % json.dumps(result["details"]) `

**Comment by synedra** [comment]
I've resolved this in the master branch.
