### ISSUE TITLE
No Python 3 support

### ISSUE THREAD

**Issue by farvour** [akamai-open/api-kickstart#7]
Hi guys. You claim your API works with "Python 2.7 or greater" which would be an untrue statement.

https://developer.akamai.com/introduction/DnLoad_Sample.html

None of the code in the contrib/python directory is directly Python 3+ compatible. Perhaps it would be a good idea to change your documentation to reflect this, or make the API work in Python 3+. The later would be preferable. :)

Thanks!

**Comment by dariusk** [comment]
Great catch. I've fixed the documentation in dev, it should be live on the site within a few hours.
